import React from 'react';
import { ReadinessReport, CompanyProfile, SavedReport } from '../../types';
import { ProgressBar } from '../ProgressBar';
import { getCompanyHeaderHtml } from '../../services/pdfUtils';
import { CheckCircle, XCircle, AlertTriangle, PlayCircle, Wrench, ListChecks, FileText, BarChart, Target, Download, Save } from 'lucide-react';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { SAVED_REPORTS_KEY } from '../../constants';

interface AnalyzerReportProps {
  report: ReadinessReport;
  onStartOver: () => void;
  companyProfile: CompanyProfile | null;
}

const getStatusIcon = (status: string) => {
  if (status === 'Met') return <CheckCircle className="h-5 w-5 text-green-500 flex-shrink-0" />;
  if (status === 'Partially Met') return <AlertTriangle className="h-5 w-5 text-yellow-500 flex-shrink-0" />;
  return <XCircle className="h-5 w-5 text-red-500 flex-shrink-0" />;
};

const getScoreColor = (score: number) => {
  if (score < 40) return 'text-red-600';
  if (score < 75) return 'text-yellow-600';
  return 'text-green-600';
};

const generateReportPdf = async (report: ReadinessReport, companyProfile: CompanyProfile | null): Promise<jsPDF> => {
    const doc = new jsPDF();
    const pageHeight = doc.internal.pageSize.height;
    const pageWidth = doc.internal.pageSize.width;
    const margin = 14;
    const primaryColor = '#0057A3';

    await doc.html(getCompanyHeaderHtml(companyProfile), {
        x: margin,
        y: 15,
        width: pageWidth - (margin * 2),
        windowWidth: 650,
    });
    
    let yPos = 90;

    const addFooter = () => {
        const pageCount = (doc as any).internal.getNumberOfPages();
        for (let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.setFontSize(9);
            doc.setTextColor(150);
            doc.text('Generated by CMMC Launch Hub', margin, pageHeight - 10);
            doc.text(`Page ${i} of ${pageCount}`, pageWidth - margin - 10, pageHeight - 10);
        }
    };
    
    // --- Cover Page ---
    doc.setFontSize(24);
    doc.setTextColor(primaryColor);
    doc.text('Security Readiness Analyzer Report', margin, yPos);
    yPos += 15;

    doc.setFillColor(240, 240, 240);
    doc.rect(margin, yPos, pageWidth - (margin * 2), 25, 'F');
    doc.setFontSize(18);
    doc.setTextColor(primaryColor);
    doc.text('Overall Readiness Score:', margin + 5, yPos + 10);
    doc.setFontSize(28);
    doc.text(`${report.overallReadinessScore}%`, margin + 5, yPos + 20);
    yPos += 40;
    
    addFooter();

    // --- Final Summary ---
    doc.addPage();
    await doc.html(getCompanyHeaderHtml(companyProfile), { x: margin, y: 15, width: pageWidth - (margin * 2), windowWidth: 650 });
    yPos = 90;
    doc.setFontSize(18).setTextColor(primaryColor).text('1. Final Summary', margin, yPos);
    yPos += 10;
    const summaryLines = [
        `Strengths: ${report.finalSummary.strengths}`,
        `Weaknesses: ${report.finalSummary.weaknesses}`,
        `Priority Actions: ${report.finalSummary.priorityActions}`,
        `Quick Wins: ${report.finalSummary.quickWins}`,
    ];
    summaryLines.forEach(line => {
        const split = doc.splitTextToSize(line, pageWidth - (margin*2));
        doc.setFontSize(11).setTextColor(0).text(split, margin, yPos);
        yPos += (split.length * 6) + 4;
    });
    
    // --- Practice Evaluation ---
    doc.addPage();
    await doc.html(getCompanyHeaderHtml(companyProfile), { x: margin, y: 15, width: pageWidth - (margin * 2), windowWidth: 650 });
    yPos = 90;
    doc.setFontSize(18).setTextColor(primaryColor).text('2. Practice-by-Practice Evaluation', margin, yPos);
    const evalBody = report.practiceEvaluation.map(p => [p.practiceId, p.status, p.summaryOfGaps, p.remediationSteps]);
    autoTable(doc, {
        startY: yPos + 5,
        head: [['Practice ID', 'Status', 'Gaps', 'Remediation']],
        body: evalBody, theme: 'striped', headStyles: { fillColor: primaryColor }
    });
    
    addFooter();
    return doc;
};


const CompanyHeader = ({ profile }: { profile: CompanyProfile | null }) => (
  <div className="flex items-start p-4 mb-6 bg-gray-50 border rounded-lg">
    {profile?.companyLogo ? (
      <img src={`data:image/png;base64,${profile.companyLogo}`} alt="Logo" className="h-16 w-auto rounded-md mr-4" />
    ) : (
      <div className="h-16 w-16 bg-gray-200 rounded-md mr-4 flex items-center justify-center text-xs text-gray-500">No Logo</div>
    )}
    <div>
      <h2 className="font-bold text-xl text-gray-800">{profile?.companyName || 'Company Name'}</h2>
      <p className="text-sm text-gray-600">{profile?.address}</p>
      <a href={profile?.website} className="text-sm text-blue-600 hover:underline">{profile?.website}</a>
    </div>
  </div>
);

export const AnalyzerReport: React.FC<AnalyzerReportProps> = ({ report, onStartOver, companyProfile }) => {

  const handleDownloadPdf = async () => {
    const doc = await generateReportPdf(report, companyProfile);
    doc.save(`CMMC_Readiness_Report_${new Date().toISOString().split('T')[0]}.pdf`);
  };

  const handleSaveReport = async () => {
    const doc = await generateReportPdf(report, companyProfile);
    const pdfDataURL = doc.output('datauristring');
    
    const savedReport: SavedReport = {
        id: crypto.randomUUID(),
        dateGenerated: new Date().toISOString(),
        readinessScore: report.overallReadinessScore,
        complianceScore: report.overallReadinessScore, // Using readiness score as a placeholder
        pdfDataURL,
    };

    try {
        const existingReports = JSON.parse(localStorage.getItem(SAVED_REPORTS_KEY) || '[]') as SavedReport[];
        localStorage.setItem(SAVED_REPORTS_KEY, JSON.stringify([...existingReports, savedReport]));
        alert('Report saved successfully!');
    } catch (error) {
        console.error('Failed to save report:', error);
        alert('Could not save the report. Local storage may be full.');
    }
  };


  return (
    <div className="bg-white p-8 rounded-lg shadow-lg border printable-report">
      <CompanyHeader profile={companyProfile} />
      {/* Header */}
      <div className="flex flex-wrap justify-between items-start border-b pb-4 mb-6 gap-4">
        <div>
          <h1 className="text-3xl font-bold text-gray-800">Security Readiness Report</h1>
          <p className="text-gray-500">Generated on {new Date().toLocaleDateString()}</p>
        </div>
        <div className="no-print flex items-center space-x-2">
            <button onClick={handleDownloadPdf} className="flex items-center px-4 py-2 text-sm bg-blue-600 text-white rounded hover:bg-blue-700">
                <Download className="h-4 w-4 mr-2"/> Download PDF
            </button>
            <button onClick={handleSaveReport} className="flex items-center px-4 py-2 text-sm bg-green-600 text-white rounded hover:bg-green-700">
                <Save className="h-4 w-4 mr-2"/> Save Report
            </button>
            <button onClick={onStartOver} className="px-4 py-2 text-sm bg-gray-600 text-white rounded hover:bg-gray-700">
                Start New Analysis
            </button>
        </div>
      </div>
      
      {/* Score and Summary */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 mb-8">
        <div className="lg:col-span-1 bg-gray-50 p-6 rounded-lg border text-center flex flex-col justify-center">
            <h2 className="text-lg font-semibold text-gray-600 mb-2">Overall Readiness Score</h2>
            <p className={`text-7xl font-bold ${getScoreColor(report.overallReadinessScore)}`}>
              {report.overallReadinessScore}%
            </p>
            <div className="mt-4">
               <ProgressBar percent={report.overallReadinessScore} />
            </div>
        </div>
        <div className="lg:col-span-2 bg-blue-50 p-6 rounded-lg border border-blue-200">
           <h2 className="text-xl font-semibold mb-3 text-blue-800 flex items-center"><Target className="h-6 w-6 mr-2" />Final Summary</h2>
           <div className="space-y-4 text-sm">
             <div><strong>Strengths:</strong> <p className="inline text-gray-700">{report.finalSummary.strengths}</p></div>
             <div><strong>Weaknesses:</strong> <p className="inline text-gray-700">{report.finalSummary.weaknesses}</p></div>
             <div><strong>Priority Actions:</strong> <p className="inline text-gray-700">{report.finalSummary.priorityActions}</p></div>
             <div><strong>Quick Wins:</strong> <p className="inline text-gray-700">{report.finalSummary.quickWins}</p></div>
           </div>
        </div>
      </div>

      {/* Practice-by-Practice Evaluation */}
      <div className="mb-8">
        <h2 className="text-2xl font-bold mb-4 flex items-center"><BarChart className="h-6 w-6 mr-2 text-blue-600" />Practice-by-Practice Evaluation</h2>
        <div className="space-y-3">
          {report.practiceEvaluation.map(p => (
            <div key={p.practiceId} className="border rounded-lg p-4 bg-gray-50">
              <div className="flex items-center space-x-3 mb-2">
                {getStatusIcon(p.status)}
                <h3 className="font-bold text-lg">{p.practiceId}</h3>
                <span className={`px-2 py-0.5 text-xs font-semibold rounded-full ${
                  p.status === 'Met' ? 'bg-green-100 text-green-800' : p.status === 'Partially Met' ? 'bg-yellow-100 text-yellow-800' : 'bg-red-100 text-red-800'
                }`}>{p.status}</span>
              </div>
              <div className="pl-8 text-sm space-y-2">
                <p><strong>Gaps:</strong> {p.summaryOfGaps}</p>
                <p><strong>Remediation:</strong> {p.remediationSteps}</p>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Implementation Plan */}
      <div className="mb-8">
          <h2 className="text-2xl font-bold mb-4 flex items-center"><PlayCircle className="h-6 w-6 mr-2 text-blue-600" />Step-by-Step Implementation Plan</h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              <div className="bg-red-50 border border-red-200 p-4 rounded-lg">
                  <h3 className="font-bold text-red-800 mb-2">Immediate (0-7 Days)</h3>
                  <ul className="list-disc pl-5 space-y-1 text-sm text-red-900">{report.implementationPlan.immediate.map((item, i) => <li key={i}>{item}</li>)}</ul>
              </div>
              <div className="bg-yellow-50 border border-yellow-200 p-4 rounded-lg">
                  <h3 className="font-bold text-yellow-800 mb-2">Short-Term (7-30 Days)</h3>
                  <ul className="list-disc pl-5 space-y-1 text-sm text-yellow-900">{report.implementationPlan.shortTerm.map((item, i) => <li key={i}>{item}</li>)}</ul>
              </div>
              <div className="bg-green-50 border border-green-200 p-4 rounded-lg">
                  <h3 className="font-bold text-green-800 mb-2">Medium-Term (30-60 Days)</h3>
                  <ul className="list-disc pl-5 space-y-1 text-sm text-green-900">{report.implementationPlan.mediumTerm.map((item, i) => <li key={i}>{item}</li>)}</ul>
              </div>
          </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Recommended Tools */}
        <div className="mb-8">
            <h2 className="text-2xl font-bold mb-4 flex items-center"><Wrench className="h-6 w-6 mr-2 text-blue-600" />Recommended Tools & Solutions</h2>
            <div className="space-y-3">
            {report.recommendedTools.map((tool, i) => (
                <div key={i} className="border rounded-lg p-3 bg-gray-50">
                <h4 className="font-semibold text-gray-800">{tool.toolType}</h4>
                <p className="text-sm text-gray-600">{tool.recommendation}</p>
                </div>
            ))}
            </div>
        </div>

        {/* Modifications to Existing Tools */}
        <div className="mb-8">
            <h2 className="text-2xl font-bold mb-4 flex items-center"><ListChecks className="h-6 w-6 mr-2 text-blue-600" />Modifications to Existing Tools</h2>
            <div className="space-y-3">
            {report.modificationsToExistingTools.map((mod, i) => (
                <div key={i} className="border rounded-lg p-3 bg-gray-50">
                <h4 className="font-semibold text-gray-800">{mod.toolName}</h4>
                <p className="text-sm text-gray-600">{mod.suggestedModifications}</p>
                </div>
            ))}
            </div>
        </div>
      </div>


      {/* Policy Requirements */}
      <div className="mb-8">
        <h2 className="text-2xl font-bold mb-4 flex items-center"><FileText className="h-6 w-6 mr-2 text-blue-600" />Policy & Procedure Requirements</h2>
        <div className="space-y-3">
          {report.policyRequirements.map((policy, i) => (
            <div key={i} className="border rounded-lg p-3 bg-gray-50">
              <h4 className="font-semibold text-gray-800">{policy.policyName}</h4>
              <p className="text-sm text-gray-600">{policy.reasoning}</p>
              <p className="text-xs mt-1 text-blue-700">Satisfies: {policy.practicesSatisfied.join(', ')}</p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};