import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { PoamItem, CompanyProfile, ResponsibilityMatrixEntry } from '../types';
import { getCompanyHeaderHtml } from './pdfUtils';

interface PoamPdfInput {
  poamItems: PoamItem[];
  companyProfile: CompanyProfile | null;
  responsibilityMatrix: ResponsibilityMatrixEntry[];
}

export const generatePoamPdf = async ({ poamItems, companyProfile, responsibilityMatrix }: PoamPdfInput) => {
  const doc = new jsPDF();
  const pageHeight = doc.internal.pageSize.height;
  const pageWidth = doc.internal.pageSize.width;
  const margin = 15;

  const headerHtml = getCompanyHeaderHtml(companyProfile);
  await doc.html(headerHtml, {
    x: margin,
    y: 15,
    width: pageWidth - (margin * 2),
    windowWidth: 650,
  });

  let yPos = 90;

  const addFooter = () => {
    const pageCount = (doc as any).internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(9);
      doc.setTextColor(150);
      doc.text('Generated by CMMC Launch Hub', margin, pageHeight - 10);
      doc.text(`Page ${i} of ${pageCount}`, pageWidth - margin, pageHeight - 10, { align: 'right' });
    }
  };

  // --- Cover Page ---
  doc.setFontSize(22);
  doc.setTextColor(40, 58, 86);
  doc.text('Plan of Action & Milestones (POA&M)', pageWidth / 2, yPos, { align: 'center' });
  yPos += 15;

  // --- Summary ---
  const openItems = poamItems.filter(p => p.status === 'open').length;
  const inProgressItems = poamItems.filter(p => p.status === 'in_progress').length;
  const completedItems = poamItems.filter(p => p.status === 'completed').length;
  const highPriority = poamItems.filter(p => p.priority === 'high' && p.status !== 'completed').length;

  autoTable(doc, {
    startY: yPos,
    head: [['Total Items', 'Open', 'In Progress', 'Completed', 'High Priority Open']],
    body: [[poamItems.length, openItems, inProgressItems, completedItems, highPriority]],
    theme: 'grid',
    headStyles: { fillColor: [40, 58, 86] }
  });
  yPos = (doc as any).lastAutoTable.finalY + 20;

  // --- Open & In-Progress Items Table ---
  doc.setFontSize(18);
  doc.text('Open & In-Progress Items', margin, yPos);
  yPos += 5;

  const openAndInProgress = poamItems.filter(p => p.status === 'open' || p.status === 'in_progress');
  if (openAndInProgress.length > 0) {
    const openTableBody = openAndInProgress.map(item => {
      const srmEntry = item.relatedPracticeIds[0] ? responsibilityMatrix.find(e => e.practiceId === item.relatedPracticeIds[0]) : undefined;
      let titleText = item.title;
      if (srmEntry) {
          titleText += `\nSRM: ${srmEntry.responsibility}, Owner: ${srmEntry.internalOwner || 'N/A'}`;
      }

      return [
        titleText,
        item.relatedPracticeIds.join(', '),
        item.priority,
        item.status,
        item.targetDate || 'N/A',
        item.owner || 'N/A'
      ];
    });
    autoTable(doc, {
      startY: yPos,
      head: [['Title', 'Practices', 'Priority', 'Status', 'Target Date', 'Owner']],
      body: openTableBody,
      theme: 'striped',
      headStyles: { fillColor: [40, 58, 86] },
      columnStyles: { 0: { cellWidth: 60 } }
    });
  } else {
    doc.setFontSize(11);
    doc.text('No open or in-progress items found.', margin, yPos + 5);
  }
  
  // --- Completed Items (if any) ---
  const completed = poamItems.filter(p => p.status === 'completed');
  if (completed.length > 0) {
    doc.addPage();
    await doc.html(headerHtml, { x: margin, y: 15, width: pageWidth - (margin * 2), windowWidth: 650 });
    yPos = 90;
    
    doc.setFontSize(18);
    doc.text('Completed Items', margin, yPos);
    yPos += 5;

    const completedTableBody = completed.map(item => {
      const srmEntry = item.relatedPracticeIds[0] ? responsibilityMatrix.find(e => e.practiceId === item.relatedPracticeIds[0]) : undefined;
      let titleText = item.title;
      if (srmEntry) {
          titleText += `\nSRM: ${srmEntry.responsibility}, Owner: ${srmEntry.internalOwner || 'N/A'}`;
      }
      return [
        titleText,
        item.relatedPracticeIds.join(', '),
        item.completedDate ? new Date(item.completedDate).toLocaleDateString() : 'N/A',
        item.owner || 'N/A'
      ];
    });

    autoTable(doc, {
      startY: yPos,
      head: [['Title', 'Practices', 'Completed Date', 'Owner']],
      body: completedTableBody,
      theme: 'striped',
      headStyles: { fillColor: [75, 85, 99] }, // Gray
      columnStyles: { 0: { cellWidth: 90 } }
    });
  }

  addFooter();
  doc.save(`POAM_${companyProfile?.companyName?.replace(/ /g, '_') || 'Report'}_${new Date().toISOString().split('T')[0]}.pdf`);
};