import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { ResponsibilityMatrixEntry, CompanyProfile } from '../types';
import { getCompanyHeaderHtml } from './pdfUtils';

interface SrmPdfInput {
  matrix: ResponsibilityMatrixEntry[];
  companyProfile: CompanyProfile | null;
}

export const generateSrmPdf = async ({ matrix, companyProfile }: SrmPdfInput) => {
  const doc = new jsPDF();
  const pageHeight = doc.internal.pageSize.height;
  const pageWidth = doc.internal.pageSize.width;
  const margin = 15;

  const headerHtml = getCompanyHeaderHtml(companyProfile);
  await doc.html(headerHtml, {
    x: margin,
    y: 15,
    width: pageWidth - (margin * 2),
    windowWidth: 650,
  });

  let yPos = 90;

  const addFooter = () => {
    const pageCount = (doc as any).internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(9);
      doc.setTextColor(150);
      doc.text('Generated by CMMC Launch Hub', margin, pageHeight - 10);
      doc.text(`Page ${i} of ${pageCount}`, pageWidth - margin, pageHeight - 10, { align: 'right' });
    }
  };

  doc.setFontSize(22);
  doc.setTextColor(40, 58, 86);
  doc.text('Shared Responsibility Matrix (SRM)', margin, yPos);
  yPos += 15;
  
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text('This matrix outlines the responsibility for each CMMC practice between the customer and service providers.', margin, yPos, { maxWidth: pageWidth - (margin * 2) });
  yPos += 15;
  
  const tableBody = matrix.map(item => [
    item.practiceId,
    item.practiceName,
    item.responsibility,
    item.providerName || 'N/A',
    item.internalOwner || 'N/A',
    item.notes || '',
  ]);
  
  autoTable(doc, {
    startY: yPos,
    head: [['Practice ID', 'Practice Name', 'Responsibility', 'Provider', 'Internal Owner', 'Notes']],
    body: tableBody,
    theme: 'striped',
    headStyles: { fillColor: [40, 58, 86] },
    columnStyles: { 
      0: { cellWidth: 20 }, 
      1: { cellWidth: 40 },
      4: { cellWidth: 30 },
      5: { cellWidth: 'auto' }
    },
    didDrawPage: () => {
      // Don't add header on every page, just footer
    }
  });

  addFooter();
  doc.save(`SRM_${companyProfile?.companyName?.replace(/ /g, '_') || 'Report'}_${new Date().toISOString().split('T')[0]}.pdf`);
};
